{
 "title": "LSB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "zoneFilter",
    "label": "Zone Filter",
    "query": {
     "query": "label_values(char_zone_gauge,zoneName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Outbound packets",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(packetType) (packet_pushes_counter{packetType=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chars per zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "char_zone_gauge{zoneName=~\"$zoneFilter\"}",
     "legendFormat": "{{zoneName}}"
    }
   ]
  },
  {
   "title": "Zone Ticks per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(zone_ticks_counter{zoneName=~\"$zoneFilter\"}[1m])",
     "legendFormat": "{{zoneName}}"
    }
   ]
  },
  {
   "title": "Chars online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (char_zone_gauge{zoneName=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Emitted packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (packet_pushes_counter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (outgoing_packet_size_counter{packetType=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}